### ISSUE TITLE
Fail to start the fcd collector

### ISSUE THREAD

**Issue by LCyson** [terra-money/fcd#147]
We're setting up a fcd node and we met this error when running the collector by `npm run collector`: 
`/blocks/1 500 - {"error":"height 1 is not available, lowest height is 4724001"}`

We want to fetch both columbus-4 and 5's information and right now we leave the `CHAIN-ID` in the `.envrc` as the default value tequilia-0004. 

Does anyone know what would be the right chain-id to use in our scenario or whether we need to change the start height in the [block.ts](https://github.com/terra-money/fcd/blob/main/src/collector/block/block.ts#L215) to other values? thanks a lot!

**Comment by LCyson** [comment]
When I tried using `CHAIN-ID=columbus-4` and manually change the start lowest height to 472001, it turns out to give me this error: 
```
APIError: /staking/validators
    at /home/ec2-user/fcd/src/lib/lcd.ts:38:13
    at tryCatcher (/home/ec2-user/fcd/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ec2-user/fcd/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/ec2-user/fcd/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/ec2-user/fcd/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/ec2-user/fcd/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/home/ec2-user/fcd/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/ec2-user/fcd/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/ec2-user/fcd/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/ec2-user/fcd/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (node:internal/timers:464:21)
```

There seems to be a compatibility issue between the version of the lcd and the fcd we're running, can anyone point a setup that works? Thanks a lot

**Comment by hanjukim** [comment]
Please use `bombay` branch and set INITIAL_HEIGHT variable (https://github.com/terra-money/fcd/tree/bombay#4-configure-environment-variables)

**Comment by LCyson** [comment]
hi @hanjukim, thanks the answer! do you by any chance know if there is a way we can load col-4 tx history onto our fcd node? or if there is a DB dump file we may use that is generated by pg_dump
