### ISSUE TITLE
Cannot destructure property 'tx_response' of '(intermediate value)' as it is undefined

### ISSUE THREAD

**Issue by kamsz** [terra-money/fcd#148]
Running bombay branch collector seems consistently crashing at specific block heights.

Columbus:
```
12-27 05:30 [INFO]: collectBlock: begin transaction for block 4822834
12-27 05:30 [ERROR]: Cannot destructure property 'tx_response' of '(intermediate value)' as it is undefined.
TypeError: Cannot destructure property 'tx_response' of '(intermediate value)' as it is undefined.
    at Object.getTx (/fcd/src/lib/lcd.ts:55:11)
    at async generateLcdTransactionToTxEntity (/fcd/src/collector/block/tx.ts:166:14)
````

Bombay:
```
12-26 23:36 [INFO]: collectBlock: begin transaction for block 6682919
12-26 23:36 [ERROR]: Cannot destructure property 'tx_response' of '(intermediate value)' as it is undefined.
TypeError: Cannot destructure property 'tx_response' of '(intermediate value)' as it is undefined.
    at Object.getTx (/fcd/src/lib/lcd.ts:55:11)
    at async generateLcdTransactionToTxEntity (/fcd/src/collector/block/tx.ts:166:14)
```

**Comment by kamsz** [comment]
Bombay calls:
```
/cosmos/tx/v1beta1/txs/C163DA039DCFFE4A640AF3816472FE05B5514FA6B1A1A5B0E505CFEEB2BC4A6F
/cosmos/tx/v1beta1/txs/26BC842EB5746200354CE0D2A1BDF50FED3354E810446D6949951F71070E9174
/cosmos/tx/v1beta1/txs/A6CE7C98469427731D946EB27684152F0966697B18687F5F2E6ABA956966CC3A
```

**Comment by kamsz** [comment]
Columbus:

```
12-27 06:27 [INFO]: collectBlock: begin transaction for block 4822834
12-27 06:27 [ERROR]: /cosmos/tx/v1beta1/txs/E1F67B0E0F7ABE9998FB38B3459DF1C68EA225200428E056943ECB217229C970
APIError: /cosmos/tx/v1beta1/txs/E1F67B0E0F7ABE9998FB38B3459DF1C68EA225200428E056943ECB217229C970
```

**Comment by hanjukim** [comment]
What LCD server do you use?

**Comment by hanjukim** [comment]
I had a similar incident in my node. The problem was that the node didn't indexed transaction somehow.

**Comment by kamsz** [comment]
What does it mean @hanjukim? How to avoid this situation? I'm using dedicated LCD (from full snapshot).

**Comment by kamsz** [comment]
@hanjukim?

**Comment by roccomuso** [comment]
any news on this?
